### ISSUE TITLE
How to convert time from military to normal time

### ISSUE THREAD

**Issue by tmartinez28** [pinsdorf/MMM-WeeklySchedule#12]
On my magicmirror, it shows the military time, how can you change it to show the normal time?

**Comment by pinsdorf** [comment]
Hello @tmartinez28, thanks for your comment.  I'm not entirely sure what you mean by "military time". I assume you refer to the clock showing "16:42" instead of "4:42pm".

If so, please check out the [Readme of the clock module](https://github.com/MichMich/MagicMirror/blob/master/modules/default/clock/README.md). It allows to configure 12/24 hour format and showing am/pm.

I close this issue as it seemy to relate to the clock module and not MMM-WeeklySchedule. Feel free to reopen with more details if it is indeed an issue of this module. Thanks.
